application:
  REMEMBER_COOKIE_HTTPONLY: true
  REMEMBER_COOKIE_NAME: TOKEN

  SESSION_COOKIE_NAME: SESSIONID
  SQLALCHEMY_DATABASE_URI: postgresql://oct:SuperS3cr3t@localhost/oct
  SQLALCHEMY_ECHO: true

  TWITTER_API:
    token: null
    token_key: null
    con_secret: null
    con_secret_key: null
